version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cafe
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db?allowPublicKeyRetrieval=true -schemas=cafe -user=root -password=password -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
    networks:
      - app_network