version: '3.8'

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: 'mysql:8.1'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cafe
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db?allowPublicKeyRetrieval=true -schemas=cafe -user=root -password=password -connectRetries=60 -cleanDisabled=false clean migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
    networks:
      - app_network
  api:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: cafe
    depends_on:
      - flyway
    ports:
      - 3000:3000
    networks:
      - app_network
  web:
    container_name: web_app
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 8080:80
    environment:
      - VITE_API_BASE_URL=http://api:3000/api/v1
    networks:
      - app_network